language: python
python:
  # - "2.7"  #Removed because of f-strings
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  # - pip install future_fstrings     #3.6 f-Strings in 2.7
  - pip install pyvisa

# command to run tests
script:
  - python -m unittest -v test.test_RSSD
  - python -m unittest -v test.test_FileIO