language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install pyvisa

# command to run tests
script:
  - python -m unittest -v test.test_RSSD